// Code generated by "stringer -type=cacheType"; DO NOT EDIT.

package main

import "strconv"

const _cacheType_name = "IssueCommentsCacheIssueTypesCacheIssuesCacheIssueCacheMyselfCachePrioritiesCacheProjectsCacheProjectCachePullRequestsCachePullRequestCommentsCacheRepositoriesCacheStatusesCacheWikisCacheWikiCache"

var _cacheType_index = [...]uint8{0, 18, 33, 44, 54, 65, 80, 93, 105, 122, 146, 163, 176, 186, 195}

func (i cacheType) String() string {
	if i < 0 || i >= cacheType(len(_cacheType_index)-1) {
		return "cacheType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _cacheType_name[_cacheType_index[i]:_cacheType_index[i+1]]
}
